Put .ts files first in the resolve order.
Now `ng1-to-ng2.ts` is used, but an error is thrown during compilation:
```
ERROR in ./~/ui-router-ng1-to-ng2/ng1-to-ng2.ts
(61,37): error TS2304: Cannot find name 'UpgradeAdapter'.
```